spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Xem_Phim?useSSL=false
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
            ddl-auto: create-drop
#            ddl-auto:  update
#      ddl-auto: none
server.port: 8086

